name: Demo test for pull request

on:
  push:
    branches:
      - new-branch

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo {{env.GIT_COMMIT_AUTHOR_NAME}} > AUTHOR

      - name: Raise pull request
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pull-request-branch"
          base: new-branch
          title: "demo pull request"
          committer: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL }}">

          body:
            This is a test for automatic pull request
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve pull request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.APPROVER_DEMO }}
          number: ${{ steps.demo-1.outputs.pull-request-number }}

      - name: Merge Pull request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo-1.outputs.pull-request-number }}
          method: squash